language: node_js
services:
node_js:
  - 0.10
  - 4
  - 6
  - 8
  - 10
  - node
before_script:
  - npm install -g grunt-cli
  - npm install -d
branches:
  only:
    - master
script:
  - npm test
after_success:
  - codeclimate < ./coverage/lcov.info
cache:
  directories:
    - "node_modules"
addons:
  code_climate:
    repo_token:
      secure: iCmhJsxfB97ahNFrko5I2fJwrpryZfzjrp9OKjcBwI8ew8+psynhy2k/5XreOjCYmrCCLU2zgOa/dhuDKP9YjCHdeE7EvUQXEfoxVuDPD7v+e3SX4wuXRpxEp1u3TAyFkTZAZ/1jF8Ja0z/hSdrQjjb4kMduUYUdtvAVu5WuaJg=
